version: '3.8'

services:
  front:
    platform: linux/x86_64
    restart: always
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --host"
    volumes:
      - ./front:/app
  back:
    build: ./backend
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: "npm run start:dev"
    volumes:
      - ./backend/src:/app/src

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
     - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./DataBase/postgres-data:/var/lib/postgresql/data

    ports:
      - "5433:5432"

volumes:
  postgres-data:
