version: '3.8'

services:
  front:
    platform: linux/x86_64
    restart: always
    build: ./front
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --host"
    volumes:
      - ./front/src:/app/src
  back:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: "npm run start:dev"
    volumes:
      - ./backend/src:/app/src

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"

volumes:
  postgres-data:
