version: '3.8'

services:
  front:
    restart: always
    build: ./front
    ports:
      - "9229:9229"
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --host"
    volumes:
      - ./front:/app
  back:
    build: ./backend
    ports: 
      - "8080:3000"
    environment:
      - NODE_ENV=development
    command: "npm run start:dev"
    volumes:
      - ./backend:/app

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
     - ./DataBase/init.sql:/docker-entrypoint-initdb.d/init.sql
     - ./DataBase/postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres-data:
