version: '3.8'

services:
  front:
    build: ./front
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --host"
    volumes:
      - ./front:/app
  back:
    build: ./backend
    ports: 
      - "8080:3000"
    environment:
      - NODE_ENV=development
    command: "npm run start:dev"
    volumes:
      - ./backend:/app